[tool.poetry]
name = "e-commerce-prog"
version = "0.1.0"
description = ""
authors = ["Irina Prokopova <irina-prokopova.style@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
